export enum ROLE {
  TEILNEHMER_DATEN_KORRIGIEREN = 'FN_WIDGET_MT_FEHLER_TN',
  CFO = 'FN_WIDGET_PC_ALL',
  PK = 'FN_WIDGET_PC_EIGEN',
  MEINE_SEMINARE = 'FN_WIDGET_MT',
  MEINE_DATEN = 'FN_WIDGET_MPD',

  MA_STAMMDATEN_ERFASSEN = 'FN_STAMMDATEN_ERFASSEN',
  MA_VERTRAGSDATEN_ERFASSEN = 'FN_VERTRAGSDATEN_ERFASSEN',
  MA_ONBOARDING = 'FN_MA_ONBOARDING',
  MA_ONBOARDING_EIGENE = 'FN_MA_ONBOARDING_EIGENE',
  MA_ONBOARDING_LV_INFORMIEREN = 'FN_MA_ONBOARDING_LV_INFORMIEREN',
  MA_UEBERPRUEFEN = 'FN_MA_UEBERPRUEFEN',
  MA_ZEITEN_LESEN = 'FN_MA_ZEITEN_LESEN',
  MA_VERWALTEN_SUCHEN = 'FN_MA_SUCHEN',

  MA_LEISTUNGEN_ERFASSEN = 'FN_MA_LEISTUNGEN_ERFASSEN', // Placeholder role for leistungen erfassen

  MA_UNTERLAGEN_LESEN = 'FN_UNTERLAGEN_LESEN',

  MA_VEREINBARUNGEN_EINSEHEN = 'FN_VEREINBARUNGEN_EINSEHEN',
  MA_ALLE_VEREINBARUNGEN_EINSEHEN = 'FN_ALLE_VEREINBARUNGEN_EINSEHEN',
  MA_VEREINBARUNGEN_ERSTELLEN = 'FN_VEREINBARUNGEN_ERSTELLEN',
  MA_UNEINGESCHRAENKTE_VEREINBARUNGEN_ERSTELLEN = 'FN_UNEINGESCHRAENKTE_VEREINBARUNGEN_ERSTELLEN',

  MA_LESEN = 'FN_MA_LESEN',
  MA_BEARBEITEN = 'FN_MA_BEARBEITEN',

  MA_VERTRAGSAENDERUNG_UEBERSICHT = 'FN_VERTRAGSAENDERUNG_UEBERSICHT',
  MA_VERTRAGSAENDERUNG_STARTEN = 'FN_VERTRAGSAENDERUNG_STARTEN',
  MA_VERTRAGSAENDERUNG_DATENVERVOLLSTAENDIGEN = 'FN_VERTRAGSAENDERUNG_DATENVERVOLLSTAENDIGEN',
  MA_VERTRAGSAENDERUNG_PRUEFEN_PEOPLE = 'FN_VERTRAGSAENDERUNG_PRUEFEN_PEOPLE',
  MA_VERTRAGSAENDERUNG_ABBRECHEN = 'FN_VERTRAGSAENDERUNG_ABBRECHEN',
  MA_VERTRAGSAENDERUNG_PRUEFEN_LOHNVERRECHNUNG = 'FN_VERTRAGSAENDERUNG_PRUEFEN_LOHNVERRECHNUNG',
  MA_VERTRAGSAENDERUNG_PRUEFEN_GENEHMIGENDEN = 'FN_VERTRAGSAENDERUNG_PRUEFEN_GENEHMIGENDEN',
  MA_VERTRAGSAENDERUNG_EINSEHEN = 'FN_VERTRAGSAENDERUNG_EINSEHEN',

  TN_LESEN = 'FN_TEILNEHMERINNEN_LESEN',
  TN_BEARBEITEN = 'FN_TEILNEHMERINNEN_BEARBEITEN',
  TN_ANLEGEN = 'FN_TEILNEHMERINNEN_ANLEGEN',
  TN_ONBOARDING = 'FN_TN_ONBOARDING',
  TN_AN_ABWESENHEITEN_UEBERTRAGEN = 'FN_TN_AN_ABWESENHEITEN_UEBERTRAGEN',
  TN_AUSTRITT = 'FN_TN_AUSTRITT',
  TN_UPLOAD_PROFIL = 'FN_TN_UPLOAD_PROFIL',

  TN_TR_ABWESENHEITEN_LESEN = 'FN_TN_TR_ABWESENHEITEN_LESEN',
  TN_ADMIN_ABWESENHEITEN_VERWALTEN = 'FN_TN_ADMIN_ABWESENHEITEN_VERWALTEN',

  TR_ANWESENHEITEN_FILTER = 'FN_TR_ANWESENHEITEN_FILTER',
  TN_TR_ANWESENHEITEN_LESEN = 'FN_TN_TR_ANWESENHEITEN_LESEN',
  TN_TR_ANWESENHEITEN_VERWALTEN = 'FN_TN_TR_ANWESENHEITEN_VERWALTEN',
  TN_ADMIN_ANWESENHEITEN_LESEN = 'FN_TN_ADMIN_ANWESENHEITEN_LESEN',
  TN_ADMIN_ANWESENHEITEN_VERWALTEN = 'FN_TN_ADMIN_ANWESENHEITEN_VERWALTEN',

  AB_ANLEGEN = 'FN_AB_ANLEGEN', // Placeholder role for Abwesenheit anlegen
  AB_ABWESENHEITEN_EDITIEREN = 'FN_ABWESENHEITEN_EDITIEREN',
  AB_EIGENE_ABWESENHEITEN_LESEN = 'FN_EIGENE_ABWESENHEITEN_LESEN',
  AB_UEBERSTUNDEN_AUSZAHLUNG = 'FN_UEBERSTUNDEN_AUSZAHLUNG',
  AB_ABWESENHEITEN_GENEHMIGEN = 'FN_ABWESENHEITEN_GENEHMIGEN', //Placeholder for Abwesenheiten genehmigen

  FN_AI_CHATBOT = 'FN_AI_CHATBOT', // Placeholder role for AI-Chatbot
  FN_REPORTS = 'FN_REPORTS', // Placeholder role for Reports
  FN_SEMINARE = 'FN_VERTRETUNGSPLANUNG',

  MA_PROJEKTE_SEMINARE_LESEN = 'FN_MA_PROJEKTE_SEMINARE_LESEN', // Admin/QA role
}
